### ISSUE TITLE
Running dev server instructions assume you have Grunt installed

### ISSUE THREAD

**Issue by zachfeldman** [lynndylanhurley/j-toker#37]
`sudo npm install -g grunt -cli` should be added to the instructions for those that don't currently have Grunt! 

Also, once I try to run Grunt, I'm faced with a pretty tragic Node error :( that's like, some kind of C level issue, solved here:
https://github.com/nodejs/node/issues/10659#issuecomment-270927364

This updated package.json.

Going to possibly keep adding things to this issue just to get up and running with devise-token-auth!

**Comment by zachfeldman** [comment]
@lynndylanhurley which version of Node was this package originally created with?

I'm realizing now it's pre React 16 so we can't just seamlessly update the versions of everything (big work there), so I wanted to try to install and run this package with older versions....but Node v0.10.48 throws a bunch of errors for me.

**Comment by lynndylanhurley** [comment]
Working on this now. I'll get you an ETA later today.

**Comment by zachfeldman** [comment]
Thank you!

**Comment by lynndylanhurley** [comment]
@zachfeldman sorry for the delay. I just updated a bunch of dependencies and set this up with yarn. Can you please try one more time?

**Comment by zachfeldman** [comment]
We have liftoff!

![image](https://user-images.githubusercontent.com/1437644/31643636-bcb27f42-b2bf-11e7-9313-76e5b8bd7d38.png)
